(cl:defpackage openpose_ros_msgs-msg
  (:use )
  (:export
   "<BODYPARTDETECTION>"
   "BODYPARTDETECTION"
   "<BODYPARTDETECTION_3D>"
   "BODYPARTDETECTION_3D"
   "<PERSONDETECTION>"
   "PERSONDETECTION"
   "<PERSONDETECTION_3D>"
   "PERSONDETECTION_3D"
  ))

