# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from openpose_ros_msgs/PersonDetection_3d.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import openpose_ros_msgs.msg

class PersonDetection_3d(genpy.Message):
  _md5sum = "d0a8af45cfc195d0d86994e1fdd9377d"
  _type = "openpose_ros_msgs/PersonDetection_3d"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 num_people_detected
uint32 person_ID
BodypartDetection_3d nose
BodypartDetection_3d neck
BodypartDetection_3d right_shoulder
BodypartDetection_3d right_elbow
BodypartDetection_3d right_wrist
BodypartDetection_3d left_shoulder
BodypartDetection_3d left_elbow
BodypartDetection_3d left_wrist
BodypartDetection_3d right_hip
BodypartDetection_3d right_knee
BodypartDetection_3d right_ankle
BodypartDetection_3d left_hip
BodypartDetection_3d left_knee
BodypartDetection_3d left_ankle
BodypartDetection_3d right_eye
BodypartDetection_3d left_eye
BodypartDetection_3d right_ear
BodypartDetection_3d left_ear
BodypartDetection_3d chest

================================================================================
MSG: openpose_ros_msgs/BodypartDetection_3d
float32 x
float32 y
float32 z
float32 confidence
"""
  __slots__ = ['num_people_detected','person_ID','nose','neck','right_shoulder','right_elbow','right_wrist','left_shoulder','left_elbow','left_wrist','right_hip','right_knee','right_ankle','left_hip','left_knee','left_ankle','right_eye','left_eye','right_ear','left_ear','chest']
  _slot_types = ['uint32','uint32','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d','openpose_ros_msgs/BodypartDetection_3d']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       num_people_detected,person_ID,nose,neck,right_shoulder,right_elbow,right_wrist,left_shoulder,left_elbow,left_wrist,right_hip,right_knee,right_ankle,left_hip,left_knee,left_ankle,right_eye,left_eye,right_ear,left_ear,chest

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PersonDetection_3d, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.num_people_detected is None:
        self.num_people_detected = 0
      if self.person_ID is None:
        self.person_ID = 0
      if self.nose is None:
        self.nose = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.neck is None:
        self.neck = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_shoulder is None:
        self.right_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_elbow is None:
        self.right_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_wrist is None:
        self.right_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_shoulder is None:
        self.left_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_elbow is None:
        self.left_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_wrist is None:
        self.left_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_hip is None:
        self.right_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_knee is None:
        self.right_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_ankle is None:
        self.right_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_hip is None:
        self.left_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_knee is None:
        self.left_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_ankle is None:
        self.left_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_eye is None:
        self.right_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_eye is None:
        self.left_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_ear is None:
        self.right_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_ear is None:
        self.left_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.chest is None:
        self.chest = openpose_ros_msgs.msg.BodypartDetection_3d()
    else:
      self.num_people_detected = 0
      self.person_ID = 0
      self.nose = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.neck = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.right_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.left_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      self.chest = openpose_ros_msgs.msg.BodypartDetection_3d()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I76f().pack(_x.num_people_detected, _x.person_ID, _x.nose.x, _x.nose.y, _x.nose.z, _x.nose.confidence, _x.neck.x, _x.neck.y, _x.neck.z, _x.neck.confidence, _x.right_shoulder.x, _x.right_shoulder.y, _x.right_shoulder.z, _x.right_shoulder.confidence, _x.right_elbow.x, _x.right_elbow.y, _x.right_elbow.z, _x.right_elbow.confidence, _x.right_wrist.x, _x.right_wrist.y, _x.right_wrist.z, _x.right_wrist.confidence, _x.left_shoulder.x, _x.left_shoulder.y, _x.left_shoulder.z, _x.left_shoulder.confidence, _x.left_elbow.x, _x.left_elbow.y, _x.left_elbow.z, _x.left_elbow.confidence, _x.left_wrist.x, _x.left_wrist.y, _x.left_wrist.z, _x.left_wrist.confidence, _x.right_hip.x, _x.right_hip.y, _x.right_hip.z, _x.right_hip.confidence, _x.right_knee.x, _x.right_knee.y, _x.right_knee.z, _x.right_knee.confidence, _x.right_ankle.x, _x.right_ankle.y, _x.right_ankle.z, _x.right_ankle.confidence, _x.left_hip.x, _x.left_hip.y, _x.left_hip.z, _x.left_hip.confidence, _x.left_knee.x, _x.left_knee.y, _x.left_knee.z, _x.left_knee.confidence, _x.left_ankle.x, _x.left_ankle.y, _x.left_ankle.z, _x.left_ankle.confidence, _x.right_eye.x, _x.right_eye.y, _x.right_eye.z, _x.right_eye.confidence, _x.left_eye.x, _x.left_eye.y, _x.left_eye.z, _x.left_eye.confidence, _x.right_ear.x, _x.right_ear.y, _x.right_ear.z, _x.right_ear.confidence, _x.left_ear.x, _x.left_ear.y, _x.left_ear.z, _x.left_ear.confidence, _x.chest.x, _x.chest.y, _x.chest.z, _x.chest.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.nose is None:
        self.nose = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.neck is None:
        self.neck = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_shoulder is None:
        self.right_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_elbow is None:
        self.right_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_wrist is None:
        self.right_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_shoulder is None:
        self.left_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_elbow is None:
        self.left_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_wrist is None:
        self.left_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_hip is None:
        self.right_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_knee is None:
        self.right_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_ankle is None:
        self.right_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_hip is None:
        self.left_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_knee is None:
        self.left_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_ankle is None:
        self.left_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_eye is None:
        self.right_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_eye is None:
        self.left_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_ear is None:
        self.right_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_ear is None:
        self.left_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.chest is None:
        self.chest = openpose_ros_msgs.msg.BodypartDetection_3d()
      end = 0
      _x = self
      start = end
      end += 312
      (_x.num_people_detected, _x.person_ID, _x.nose.x, _x.nose.y, _x.nose.z, _x.nose.confidence, _x.neck.x, _x.neck.y, _x.neck.z, _x.neck.confidence, _x.right_shoulder.x, _x.right_shoulder.y, _x.right_shoulder.z, _x.right_shoulder.confidence, _x.right_elbow.x, _x.right_elbow.y, _x.right_elbow.z, _x.right_elbow.confidence, _x.right_wrist.x, _x.right_wrist.y, _x.right_wrist.z, _x.right_wrist.confidence, _x.left_shoulder.x, _x.left_shoulder.y, _x.left_shoulder.z, _x.left_shoulder.confidence, _x.left_elbow.x, _x.left_elbow.y, _x.left_elbow.z, _x.left_elbow.confidence, _x.left_wrist.x, _x.left_wrist.y, _x.left_wrist.z, _x.left_wrist.confidence, _x.right_hip.x, _x.right_hip.y, _x.right_hip.z, _x.right_hip.confidence, _x.right_knee.x, _x.right_knee.y, _x.right_knee.z, _x.right_knee.confidence, _x.right_ankle.x, _x.right_ankle.y, _x.right_ankle.z, _x.right_ankle.confidence, _x.left_hip.x, _x.left_hip.y, _x.left_hip.z, _x.left_hip.confidence, _x.left_knee.x, _x.left_knee.y, _x.left_knee.z, _x.left_knee.confidence, _x.left_ankle.x, _x.left_ankle.y, _x.left_ankle.z, _x.left_ankle.confidence, _x.right_eye.x, _x.right_eye.y, _x.right_eye.z, _x.right_eye.confidence, _x.left_eye.x, _x.left_eye.y, _x.left_eye.z, _x.left_eye.confidence, _x.right_ear.x, _x.right_ear.y, _x.right_ear.z, _x.right_ear.confidence, _x.left_ear.x, _x.left_ear.y, _x.left_ear.z, _x.left_ear.confidence, _x.chest.x, _x.chest.y, _x.chest.z, _x.chest.confidence,) = _get_struct_2I76f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I76f().pack(_x.num_people_detected, _x.person_ID, _x.nose.x, _x.nose.y, _x.nose.z, _x.nose.confidence, _x.neck.x, _x.neck.y, _x.neck.z, _x.neck.confidence, _x.right_shoulder.x, _x.right_shoulder.y, _x.right_shoulder.z, _x.right_shoulder.confidence, _x.right_elbow.x, _x.right_elbow.y, _x.right_elbow.z, _x.right_elbow.confidence, _x.right_wrist.x, _x.right_wrist.y, _x.right_wrist.z, _x.right_wrist.confidence, _x.left_shoulder.x, _x.left_shoulder.y, _x.left_shoulder.z, _x.left_shoulder.confidence, _x.left_elbow.x, _x.left_elbow.y, _x.left_elbow.z, _x.left_elbow.confidence, _x.left_wrist.x, _x.left_wrist.y, _x.left_wrist.z, _x.left_wrist.confidence, _x.right_hip.x, _x.right_hip.y, _x.right_hip.z, _x.right_hip.confidence, _x.right_knee.x, _x.right_knee.y, _x.right_knee.z, _x.right_knee.confidence, _x.right_ankle.x, _x.right_ankle.y, _x.right_ankle.z, _x.right_ankle.confidence, _x.left_hip.x, _x.left_hip.y, _x.left_hip.z, _x.left_hip.confidence, _x.left_knee.x, _x.left_knee.y, _x.left_knee.z, _x.left_knee.confidence, _x.left_ankle.x, _x.left_ankle.y, _x.left_ankle.z, _x.left_ankle.confidence, _x.right_eye.x, _x.right_eye.y, _x.right_eye.z, _x.right_eye.confidence, _x.left_eye.x, _x.left_eye.y, _x.left_eye.z, _x.left_eye.confidence, _x.right_ear.x, _x.right_ear.y, _x.right_ear.z, _x.right_ear.confidence, _x.left_ear.x, _x.left_ear.y, _x.left_ear.z, _x.left_ear.confidence, _x.chest.x, _x.chest.y, _x.chest.z, _x.chest.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.nose is None:
        self.nose = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.neck is None:
        self.neck = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_shoulder is None:
        self.right_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_elbow is None:
        self.right_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_wrist is None:
        self.right_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_shoulder is None:
        self.left_shoulder = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_elbow is None:
        self.left_elbow = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_wrist is None:
        self.left_wrist = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_hip is None:
        self.right_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_knee is None:
        self.right_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_ankle is None:
        self.right_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_hip is None:
        self.left_hip = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_knee is None:
        self.left_knee = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_ankle is None:
        self.left_ankle = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_eye is None:
        self.right_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_eye is None:
        self.left_eye = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.right_ear is None:
        self.right_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.left_ear is None:
        self.left_ear = openpose_ros_msgs.msg.BodypartDetection_3d()
      if self.chest is None:
        self.chest = openpose_ros_msgs.msg.BodypartDetection_3d()
      end = 0
      _x = self
      start = end
      end += 312
      (_x.num_people_detected, _x.person_ID, _x.nose.x, _x.nose.y, _x.nose.z, _x.nose.confidence, _x.neck.x, _x.neck.y, _x.neck.z, _x.neck.confidence, _x.right_shoulder.x, _x.right_shoulder.y, _x.right_shoulder.z, _x.right_shoulder.confidence, _x.right_elbow.x, _x.right_elbow.y, _x.right_elbow.z, _x.right_elbow.confidence, _x.right_wrist.x, _x.right_wrist.y, _x.right_wrist.z, _x.right_wrist.confidence, _x.left_shoulder.x, _x.left_shoulder.y, _x.left_shoulder.z, _x.left_shoulder.confidence, _x.left_elbow.x, _x.left_elbow.y, _x.left_elbow.z, _x.left_elbow.confidence, _x.left_wrist.x, _x.left_wrist.y, _x.left_wrist.z, _x.left_wrist.confidence, _x.right_hip.x, _x.right_hip.y, _x.right_hip.z, _x.right_hip.confidence, _x.right_knee.x, _x.right_knee.y, _x.right_knee.z, _x.right_knee.confidence, _x.right_ankle.x, _x.right_ankle.y, _x.right_ankle.z, _x.right_ankle.confidence, _x.left_hip.x, _x.left_hip.y, _x.left_hip.z, _x.left_hip.confidence, _x.left_knee.x, _x.left_knee.y, _x.left_knee.z, _x.left_knee.confidence, _x.left_ankle.x, _x.left_ankle.y, _x.left_ankle.z, _x.left_ankle.confidence, _x.right_eye.x, _x.right_eye.y, _x.right_eye.z, _x.right_eye.confidence, _x.left_eye.x, _x.left_eye.y, _x.left_eye.z, _x.left_eye.confidence, _x.right_ear.x, _x.right_ear.y, _x.right_ear.z, _x.right_ear.confidence, _x.left_ear.x, _x.left_ear.y, _x.left_ear.z, _x.left_ear.confidence, _x.chest.x, _x.chest.y, _x.chest.z, _x.chest.confidence,) = _get_struct_2I76f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I76f = None
def _get_struct_2I76f():
    global _struct_2I76f
    if _struct_2I76f is None:
        _struct_2I76f = struct.Struct("<2I76f")
    return _struct_2I76f
