// Generated by gencpp from file openpose_ros_msgs/GetPersonsResponse.msg
// DO NOT EDIT!


#ifndef OPENPOSE_ROS_MSGS_MESSAGE_GETPERSONSRESPONSE_H
#define OPENPOSE_ROS_MSGS_MESSAGE_GETPERSONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <openpose_ros_msgs/PersonDetection.h>

namespace openpose_ros_msgs
{
template <class ContainerAllocator>
struct GetPersonsResponse_
{
  typedef GetPersonsResponse_<ContainerAllocator> Type;

  GetPersonsResponse_()
    : detections()  {
    }
  GetPersonsResponse_(const ContainerAllocator& _alloc)
    : detections(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::openpose_ros_msgs::PersonDetection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpose_ros_msgs::PersonDetection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPersonsResponse_

typedef ::openpose_ros_msgs::GetPersonsResponse_<std::allocator<void> > GetPersonsResponse;

typedef boost::shared_ptr< ::openpose_ros_msgs::GetPersonsResponse > GetPersonsResponsePtr;
typedef boost::shared_ptr< ::openpose_ros_msgs::GetPersonsResponse const> GetPersonsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openpose_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'openpose_ros_msgs': ['/home/fetchbot/catkin_ws/src/openpose_ros_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c7fca3a20ea0f816b81a15333fcfc4b";
  }

  static const char* value(const ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c7fca3a20ea0f81ULL;
  static const uint64_t static_value2 = 0x6b81a15333fcfc4bULL;
};

template<class ContainerAllocator>
struct DataType< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpose_ros_msgs/GetPersonsResponse";
  }

  static const char* value(const ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PersonDetection[] detections\n\
\n\
================================================================================\n\
MSG: openpose_ros_msgs/PersonDetection\n\
uint32 num_people_detected\n\
uint32 person_ID\n\
BodypartDetection nose\n\
BodypartDetection neck\n\
BodypartDetection right_shoulder\n\
BodypartDetection right_elbow\n\
BodypartDetection right_wrist\n\
BodypartDetection left_shoulder\n\
BodypartDetection left_elbow\n\
BodypartDetection left_wrist\n\
BodypartDetection right_hip\n\
BodypartDetection right_knee\n\
BodypartDetection right_ankle\n\
BodypartDetection left_hip\n\
BodypartDetection left_knee\n\
BodypartDetection left_ankle\n\
BodypartDetection right_eye\n\
BodypartDetection left_eye\n\
BodypartDetection right_ear\n\
BodypartDetection left_ear\n\
BodypartDetection chest\n\
\n\
================================================================================\n\
MSG: openpose_ros_msgs/BodypartDetection\n\
uint32 x\n\
uint32 y\n\
float32 confidence\n\
";
  }

  static const char* value(const ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPersonsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpose_ros_msgs::GetPersonsResponse_<ContainerAllocator>& v)
  {
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpose_ros_msgs::PersonDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPOSE_ROS_MSGS_MESSAGE_GETPERSONSRESPONSE_H
